Repository team-windup/highpitch, pull requests merged in 2023-11, with the labels that each got.

#2 [Setting] My First Commit #1
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/HighPitchApp.swift
Labels: Chore

#3 [Feat] 오디오 퍼미션 팝오버 뷰 작성 #1
  highpitch.xcodeproj/project.pbxproj
  highpitch/Managers/SystemManager.swift
  highpitch/Presentation/MainWindow/Common/Popover/RequestAudioPermissionPopover.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Store/PracticeViewStore.swift
  highpitch/Resource/Assets.xcassets/audioSetting.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/audioSetting.imageset/audioSetting.png
  highpitch/Resource/Assets.xcassets/hp-logo.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/hp-logo.imageset/hp-logo.png
Labels: Setting

#6 [Feat] 오디오 허가 팝업 개발 #5
  highpitch.xcodeproj/project.pbxproj
  highpitch/Managers/MediaManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Managers/SystemManager.swift
  highpitch/Presentation/MainWindow/Common/Popover/RequestAudioPermissionPopover.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
Labels: Feat

#7 [Refactor] PracticeView ViewStore 추가
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/HighPitchApp.swift
  highpitch/DesignSystem/Components/Common/HPTopToolbar.swift
  highpitch/Managers/ProjectManagers/AppleScriptManager.swift
  highpitch/Managers/ProjectManagers/KeynoteManager.swift
  highpitch/Managers/ProjectManagers/PracticeManager.swift
  highpitch/Managers/ProjectManagers/ProjectManager.swift
  highpitch/Managers/SystemManagers/AuthManager.swift
  highpitch/Managers/SystemManagers/FileSystemManager.swift
  highpitch/Managers/SystemManagers/GAManager.swift
  highpitch/Managers/SystemManagers/KeychainManager.swift
  highpitch/Managers/SystemManagers/MediaManager.swift
  highpitch/Managers/SystemManagers/NotificationManager.swift
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Managers/SystemManagers/SystemManager.swift
  highpitch/Models/DataModels/APIModels/ReturnZeroModels/TokenData.swift
  highpitch/Models/DataModels/ProjectModels/AppleScript.swift
  highpitch/Models/DataModels/ProjectModels/OpendKeynote.swift
  highpitch/Models/DataModels/ProjectModels/SentenceInfo.swift
  highpitch/Models/DataModels/ProjectModels/Utterance.swift
  highpitch/Models/PersistenceModels/PracticeSummaryModel.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeList.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordChart/FillerWordDetail/FillerWordDetail.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordChart/FillerWordDetail/FillerWordDetailCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordChart/FillerWordList.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordChart/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordChart/UsageTopTierChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordDetail.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SlowSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedChart/FastSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedChart/SentenceCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedChart/SlowSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedChart/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Popover/PracticeInfoPopover.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Sheet/EPMSheet.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Sheet/FillerWordSheet.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Store/PracticeViewStore.swift
Labels: Refactor

#9 [Feat] 항상 위에 뜨는 NSPanel 추가
  highpitch/App/HighPitchApp.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
Labels: Feat

#13 Feat/#11 실시간 분석 추가
  .gitignore
  .swiftlint.yml
  highpitch.xcodeproj/project.pbxproj
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
Labels: Feat

#15 [Feat] Panel 4개 생성
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/HighPitchApp.swift
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
  highpitch/Presentation/Overlay/PanelData.swift
  highpitch/Presentation/Overlay/SettingPanelView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
  highpitch/Presentation/Overlay/TimerPanelView.swift
Labels: Feat

#16 [Fix] appDelegate 사용하는 부분 주석
  highpitch/App/HighPitchApp.swift
Labels: Fix

#17 [Feat] 프로젝트 이름 클릭하면 Panel들 등장 toggle
  highpitch/App/HighPitchApp.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/Overlay/PanelData.swift
Labels: Feat

#18 Feat/#11 systemManager 수정
  highpitch.xcodeproj/project.pbxproj
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Managers/SystemManagers/SystemManager.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/Overlay/PanelData.swift
Labels: Feat

#20 [Design] filler word panel 디자인
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
Labels: Design

#21 [Feat] PracticeView 상세 디자인 수정 및 인스턴트 피드백 뷰 디자인
  highpitch.xcodeproj/project.pbxproj
  highpitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  highpitch/App/AppDelegate.swift
  highpitch/Managers/TestManagers/SwiftDataMockManager.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedChart/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Store/PracticeViewStore.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/FullScreenVideoContainer/FullScreenVideoContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/PracticeContentContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/FeedbackContent/FeedbackStyleScript.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/SplitViewContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/VideoContainer/VideoContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/AudioIndicator/FillerWordAudioIndicator.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/AudioIndicator/SpeedAudioIndicator.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/VideoControllerContainer.swift
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
  highpitch/Resource/Embaded/20231107202138.m4a
  highpitch/Utils/Modifier/ShapeModifier.swift
Labels: Design, Feat

#23 [Test] 말빠르기 패널 테스트 #8
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
Labels: Chore

#25 [Feat] 스크린 녹화 기능 구현 #22
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/highpitch.entitlements
  highpitch/Managers/SystemManagers/ScreenRecordManager/CaptureEngine.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/ChaptuerPreview.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/ChaptureEngineForPreview.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/ScreenRecordManager.swift
  highpitch/Presentation/MainWindow/ScreenRecordView/ScreenItemView.swift
  highpitch/Presentation/MainWindow/ScreenRecordView/ScreenSelectionView.swift
Labels: Feat

#26 [Feat] return zero speech로 대체
  highpitch/Managers/ProjectManagers/ProjectManager.swift
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
Labels: Feat

#27 [Fix] speech recognizer error fixed
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
Labels: Fix

#29 [Fix] 피드백 반영사항 수정
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/FullScreenVideoContainer/FullScreenVideoContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/PracticeContentContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/FeedbackContent/FeedbackStyleScript.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/VideoContainer/VideoContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/AudioIndicator/FillerWordAudioIndicator.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/AudioIndicator/SpeedAudioIndicator.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
  highpitch/Presentation/Overlay/TimerPanelView.swift
  highpitch/Resource/Assets.xcassets/expandVideo.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/expandVideo.imageset/ant-design_expand-outlined.svg
Labels: Fix

#30 [Feat] Panel 기능 추가 및 디자인 수정
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/AppDelegate.swift
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/SystemManagers/InstantFeedbackManager.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/Overlay/EditPanelView.swift
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
  highpitch/Presentation/Overlay/PanelController.swift
  highpitch/Presentation/Overlay/PanelData.swift
  highpitch/Presentation/Overlay/SettingPanelView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
  highpitch/Presentation/Overlay/TimerPanelView.swift
Labels: Feat

#32 [Feat] SwiftData Version 관리 구현
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/HighPitchApp.swift
  highpitch/Models/SchemaMigrationPlan/SchemaMigrationPlan.swift
  highpitch/Models/VersionedSchema/VersionedSchema1.swift
  highpitch/Models/VersionedSchema/VersionedSchema2.swift
Labels: Feat

#33 [Feat] SwiftData Schema 및 MigrationPlan 추가
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/ProjectManagers/PracticeManager.swift
  highpitch/Managers/TestManagers/SwiftDataMockManager.swift
  highpitch/Models/PersistenceModels/PracticeModel.swift
  highpitch/Models/PersistenceModels/PracticeSummaryModel.swift
  highpitch/Models/PersistenceModels/ProjectModel.swift
  highpitch/Models/PersistenceModels/SentenceModel.swift
  highpitch/Models/SchemaMigrationPlan/SchemaMigrationPlan.swift
  highpitch/Models/VersionedSchema/VersionedSchema1.swift
  highpitch/Models/VersionedSchema/VersionedSchema2.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordChart/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectView.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticTabGraph.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift
Labels: Feat

#34 [Chore] 디자인 수정사항 반영 #8
  highpitch.xcodeproj/project.pbxproj
  highpitch/DesignSystem/Components/Common/HPTopToolbar.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectLinkItem/ProjectLinkItem.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeList.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectView.swift
Labels: Design, Chore

#38 [Feat] PracticeManager 변경 완료
  highpitch/Managers/ProjectManagers/PracticeManager.swift
  highpitch/Managers/ProjectManagers/ProjectManager.swift
  highpitch/Managers/TestManagers/SwiftDataMockManager.swift
  highpitch/Models/PersistenceModels/PracticeModel.swift
  highpitch/Models/PersistenceModels/PracticeSummaryModel.swift
  highpitch/Models/PersistenceModels/SentenceModel.swift
Labels: Feat

#43 [Design] MainWindow 전반적인 0.2.0 디자인 적용
  highpitch/App/HighPitchApp.swift
  highpitch/DesignSystem/Components/Common/HPTopToolbar.swift
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/6_Component/audiocontroller.colorset/Contents.json
  highpitch/Models/PersistenceModels/SentenceModel.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeList.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Store/PracticeViewStore.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/FeedbackContent/FeedbackStyleScript.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/FeedbackContent/FillerWordFeedbackContent.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/PracticeDetailContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/AudioIndicator/FillerWordAudioIndicator.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/AudioIndicator/SpeedAudioIndicator.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/VideoControllerContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectView.swift
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
Labels: Design

#45 [Feat] MenubarExtra 코드 수정 및 프로젝트 내 연습하기 추가
  highpitch/App/HighPitchApp.swift
  highpitch/DesignSystem/Components/Common/HPArcodianView.swift
  highpitch/DesignSystem/Components/Common/HPMenu.swift
  highpitch/Managers/ProjectManagers/ProjectManager.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordChart/FillerWordDetail/FillerWordDetail.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordChart/FillerWordDetail/FillerWordDetailCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordChart/UsageTopTierChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/FeedbackContent/FillerWordFeedbackContent.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectOutLine.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraContent/MenubarExtraContent.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
Labels: Feat

#46 [Feat] 스크린 캡쳐 로직 구현 #22
  highpitch.xcodeproj/project.pbxproj
  highpitch/APIs/ReturnZero/ReturnzeroAPIV2.swift
  highpitch/App/HighPitchApp.swift
  highpitch/App/highpitch.entitlements
  highpitch/Managers/ProjectManagers/ProjectManager.swift
  highpitch/Managers/SystemManagers/MediaManager.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/AudioRecorder.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/CaptureEngine.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/ChaptuerPreview.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/ScreenRecordManager.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/VideoWithAudioRecordEngine.swift
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Models/DataModels/ProjectModels/OpendKeynote.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ScreenRecordView/ScreenItemView.swift
  highpitch/Presentation/MainWindow/ScreenRecordView/ScreenSelectionView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Utils/Extension/URL+Extension.swift
Labels: Feat

#48 [Feat] 내 연습 분석 뷰
  highpitch/Managers/ProjectManagers/ProjectManager.swift
  highpitch/Presentation/MainWindow/AnalysisView/AnalysisFWPMChart.swift
  highpitch/Presentation/MainWindow/AnalysisView/AnalysisSpeedRateChart.swift
  highpitch/Presentation/MainWindow/AnalysisView/PracticeAnalysisView.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectFWPMChart.swift
Labels: Design, Feat

#50 [Fix] speaking rate instant feedback 조정
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
Labels: Fix, Feat

#51 [Feat] NSPanel 기능 구현
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/AppDelegate.swift
  highpitch/Managers/SystemManagers/InstantFeedbackManager.swift
  highpitch/Models/VersionedSchema/VersionedSchema2.swift
  highpitch/Presentation/Overlay/EditPanelView.swift
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
  highpitch/Presentation/Overlay/PanelController.swift
  highpitch/Presentation/Overlay/RecordPanelView.swift
  highpitch/Presentation/Overlay/SavePanelView.swift
  highpitch/Presentation/Overlay/SettingPanelView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
  highpitch/Presentation/Overlay/TimerPanelView.swift
Labels: Feat

#54 [Refactor] 프로젝트 내 키노트 관련 제거, 연습 플로우 세팅
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/AppDelegate.swift
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/ProjectManagers/AppleScriptManager.swift
  highpitch/Managers/ProjectManagers/KeynoteManager.swift
  highpitch/Managers/ProjectManagers/ProjectManager.swift
  highpitch/Managers/SystemManagers/FileSystemManager.swift
  highpitch/Managers/SystemManagers/SystemManager.swift
  highpitch/Models/DataModels/ProjectModels/AppleScript.swift
  highpitch/Models/DataModels/ProjectModels/OpendKeynote.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/OnboardingView/OnboardingView.swift
  highpitch/Presentation/MainWindow/OnboardingView/SpeechTestView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ScreenRecordView/ScreenSelectionView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraContent/MenubarExtraContent.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/Presentation/Overlay/SavePanelView.swift
  highpitch/Resource/Assets.xcassets/onboarding/Contents.json
  highpitch/Resource/Assets.xcassets/onboarding/appIcon.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/onboarding/appIcon.imageset/appIcon.png
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_1.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_1.imageset/Onboarding_1.jpg
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_2.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_2.imageset/Onboarding_2.jpg
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_3.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_3.imageset/Onboarding_3.jpg
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_4.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_4.imageset/Onboarding_4.jpg
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_6.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_6.imageset/Onboarding_5.jpg
Labels: Fix, Refactor, Feat

#55 [Fix] NSPanel 위치 재설정
  highpitch/App/AppDelegate.swift
  highpitch/Presentation/Overlay/EditPanelView.swift
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
  highpitch/Presentation/Overlay/SavePanelView.swift
  highpitch/Presentation/Overlay/SettingPanelView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
  highpitch/Presentation/Overlay/TimerPanelView.swift
Labels: Fix

#56 [Fix] few bug fixed
  highpitch.xcodeproj/project.pbxproj
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Presentation/MainWindow/AnalysisView/AnalysisSpeedRateChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeList.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Store/PracticeViewStore.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/FullScreenVideoContainer/FullScreenVideoContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/PracticeContentContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/FeedbackContent/EveryFeedbackContent.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/FeedbackContent/FeedbackStyleScript.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/FeedbackContent/FillerWordFeedbackContent.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/PracticeDetailContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/ReportContent/ReportView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/SplitViewContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/VideoContainer/VideoContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/AudioIndicator/FillerWordAudioIndicator.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/AudioIndicator/SpeedAudioIndicator.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/VideoControllerContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectSpeakingRateChart.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
Labels: Fix

#57 [Feat] 비디오 재생 로직 추가 #47
  highpitch.xcodeproj/project.pbxproj
  highpitch/Managers/ProjectManagers/ProjectManager.swift
  highpitch/Managers/SystemManagers/MediaManager.swift
  highpitch/Models/PersistenceModels/PracticeModel.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/FullScreenVideoContainer/FullScreenVideoContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/PracticeContentContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/VideoContainer/VideoContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/VideoContainer/VideoView.swift
Labels: Feat

#59 [Feat] 프리뷰에 디스플레이 추가 #58
  highpitch/Managers/ProjectManagers/ProjectManager.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/CaptureEngine.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/ChaptuerPreview.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/ChaptureEngineForPreview.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/ScreenRecordManager.swift
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Presentation/MainWindow/ScreenRecordView/ScreenSelectionView.swift
Labels: Feat

#65 [Design][Feat] sidebar 작업 완료
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectLinkItem/ProjectLinkItem.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Store/PracticeViewStore.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/ReportContent/ReportSpeakingRateChart.swift
Labels: Design, Feat

#66 [Feat] 비디오 키 추가 및 현재 시간 문장 찾기 기능 추가 #58
  highpitch/Managers/SystemManagers/MediaManager.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/PracticeContentContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/FeedbackContent/FeedbackStyleScript.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/VideoContainer/VideoView.swift
Labels: Feat

#68 [Feat] 문장 업데이트 로직 수정 #58
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Store/PracticeViewStore.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/FeedbackContent/FeedbackStyleScript.swift
Labels: Feat

#71 [Fix] speech recognizer 문장 누락 버그 픽스
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
Labels: Fix

#72 [Fix] NSPanel 위치 불러오기
  highpitch/App/AppDelegate.swift
  highpitch/Managers/SystemManagers/InstantFeedbackManager.swift
  highpitch/Managers/SystemManagers/ScreenRecordManager/AudioRecorder.swift
  highpitch/Managers/SystemManagers/SystemManager.swift
  highpitch/Presentation/Overlay/EditPanelView.swift
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
  highpitch/Presentation/Overlay/PanelController.swift
  highpitch/Presentation/Overlay/SavePanelView.swift
  highpitch/Presentation/Overlay/SettingPanelView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
  highpitch/Presentation/Overlay/TimerPanelView.swift
Labels: Fix

#74 [Chore] 전반적인 디자인 사항 반영
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/HighPitchApp.swift
  highpitch/DesignSystem/Components/Common/HPHoverBox.swift
  highpitch/DesignSystem/Components/Common/HPTopToolbar.swift
  highpitch/DesignSystem/Foundation/Typography/Typography.swift
  highpitch/Managers/SystemManagers/SystemManager.swift
  highpitch/Presentation/MainWindow/AnalysisView/PracticeAnalysisView.swift
  highpitch/Presentation/MainWindow/Common/Sheet/MainWindowPracticeSaveSheet.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/OnboardingView/SpeechTestView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeList.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Store/PracticeViewStore.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/FullScreenVideoContainer/FullScreenVideoContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/PracticeDetailContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/ReportContent/ReportView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/VideoContainer/VideoContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/AudioIndicator/HPSlider.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/VideoControllerContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectOutLine.swift
  highpitch/Presentation/MainWindow/ScreenRecordView/ScreenSelectionView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/Settings/SettingsView.swift
  highpitch/Resource/Assets.xcassets/reduceVideo.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/reduceVideo.imageset/screenSize.png
Labels: Fix, Design, Chore

#77 [Fix] fixed with chart hover
  highpitch/Presentation/MainWindow/ProjectView/ProjectFWPMChart.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectLengthChart.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectSpeakingRateChart.swift
Labels: Fix

#80 [Fix] QA사항 반영
  highpitch/App/HighPitchApp.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectLinkItem/ProjectLinkItem.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeList.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectOutLine.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraContent/MenubarExtraContent.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
Labels: Fix

#82 [Fix] Panel 일부 수정
  highpitch.xcodeproj/project.pbxproj
  highpitch/Managers/SystemManagers/SystemManager.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/Overlay/EditPanelView.swift
  highpitch/Presentation/Overlay/RecordPanelView.swift
  highpitch/Presentation/Overlay/SavePanelView.swift
  highpitch/SeretKey.plist
Labels: Fix

#87 [Feat] 받아쓰기 활성화 확인 로릭 추가 #84
  highpitch.xcodeproj/project.pbxproj
  highpitch/Managers/SystemManagers/MediaManager.swift
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Presentation/MainWindow/Common/Sheet/RequestDictationView.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
Labels: Feat

#88 [Fix] 디자인 QA 적용
  highpitch/DesignSystem/Components/Common/HPMenu.swift
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Presentation/MainWindow/AnalysisView/AnalysisFWPMChart.swift
  highpitch/Presentation/MainWindow/OnboardingView/OnboardingView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeList.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/ReportContent/ReportSpeakingRateChart.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectFWPMChart.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraFooter/MenubarExtraFooter.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
  highpitch/Utils/Extension/Date+Extension.swift
Labels: Fix

#90 [Fix] NSPanel 위치 저장 수정 및 연습 저장하지 않기 구현
  highpitch/App/AppDelegate.swift
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/ProjectManagers/ProjectManager.swift
  highpitch/Managers/SystemManagers/InstantFeedbackManager.swift
  highpitch/Managers/SystemManagers/SystemManager.swift
  highpitch/Presentation/MainWindow/Common/Sheet/MainWindowPracticeSaveSheet.swift
  highpitch/Presentation/MainWindow/ScreenRecordView/ScreenSelectionView.swift
  highpitch/Presentation/Overlay/EditPanelView.swift
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
  highpitch/Presentation/Overlay/RecordPanelView.swift
  highpitch/Presentation/Overlay/SavePanelView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
  highpitch/Presentation/Overlay/TimerPanelView.swift
Labels: Fix
