Repository team-windup/highpitch, pull requests merged in 2023-12, with the labels that each got.

#91 [Fix] 디자인 QA 적용
  highpitch/App/AppDelegate.swift
  highpitch/App/HighPitchApp.swift
  highpitch/DesignSystem/Components/Common/HPArcodianView.swift
  highpitch/DesignSystem/Components/Common/HPHoverBox.swift
  highpitch/DesignSystem/Components/Core/HPLabel/HPLabel.swift
  highpitch/DesignSystem/Foundation/Colors/Colors.swift
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/4_ColorScale/Blue/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/4_ColorScale/Blue/blue300.colorset/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/4_ColorScale/Blue/blue500.colorset/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/5_TextStyle/textWhite1000.colorset/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/5_TextStyle/textWhite800.colorset/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/6_Component/Onboarding/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/6_Component/Onboarding/onboardingbackground.colorset/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/6_Component/SpeedFeedback/highlightslowbackground.colorset/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/6_Component/SpeedFeedback/highlightslowpoint.colorset/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/6_Component/SpeedFeedback/instantslow300.colorset/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/6_Component/SpeedFeedback/instantslow500.colorset/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/6_Component/timegrpah.colorset/Contents.json
  highpitch/Managers/SystemManagers/InstantFeedbackManager.swift
  highpitch/Presentation/MainWindow/AnalysisView/AnalysisSpeedRateChart.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/OnboardingView/OnboardingView.swift
  highpitch/Presentation/MainWindow/OnboardingView/sheet/RequestMicPermissionSheet.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeList.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Store/PracticeViewStore.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/FullScreenVideoContainer/FullScreenVideoContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/PracticeContentContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/FeedbackContent/FeedbackStyleScript.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/PracticeDetailContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/VideoContainer/VideoContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/AudioIndicator/FillerWordAudioIndicator.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/AudioIndicator/HPSlider.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/VideoControllerContainer/AudioIndicator/SpeedAudioIndicator.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectLengthChart.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectSpeakingRateChart.swift
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
  highpitch/Presentation/Overlay/SettingPanelView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
  highpitch/Presentation/Overlay/TimerPanelView.swift
  highpitch/Presentation/Settings/SettingsView.swift
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_1.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_1.imageset/Onboarding_1 1.jpg
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_2.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_2.imageset/Onboarding_2 1.jpg
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_3.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_3.imageset/Onboarding_3 1.jpg
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_4.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_4.imageset/Onboarding_4 1.jpg
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_6.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/onboarding/onboarding_6.imageset/Onboarding_5 1.jpg
Labels: Fix

#93 [Fix] few bug fix
  .swiftlint.yml
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/SystemManagers/MediaManager.swift
  highpitch/Managers/SystemManagers/SpeechRecognizerManager.swift
  highpitch/Models/DataModels/ProjectModels/Utterance.swift
  highpitch/Models/PersistenceModels/PracticeModel.swift
  highpitch/Models/PersistenceModels/UtteranceModel.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/Store/PracticeViewStore.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/PracticeContentContainer.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/v0.2.0/SplitViewContainer/PracticeDetailContainer/FeedbackContent/FeedbackStyleScript.swift
Labels: Fix

#94 [Fix] 연습 저장하지 않기 기능 수정
  highpitch/App/AppDelegate.swift
  highpitch/Managers/ProjectManagers/ProjectManager.swift
  highpitch/Models/PersistenceModels/UtteranceModel.swift
  highpitch/Presentation/MainWindow/Common/Sheet/MainWindowPracticeSaveSheet.swift
  highpitch/Presentation/MainWindow/ScreenRecordView/ScreenSelectionView.swift
  highpitch/Presentation/Overlay/EditPanelView.swift
  highpitch/Presentation/Overlay/FillerWordPanelView.swift
  highpitch/Presentation/Overlay/SavePanelView.swift
  highpitch/Presentation/Overlay/SpeedPanelView.swift
  highpitch/Presentation/Overlay/TimerPanelView.swift
Labels: Fix

#96 [Add] TimerPanel 클릭 시 타이머 동작 추가
  highpitch/Presentation/Overlay/TimerPanelView.swift
Labels: Add

#99 [Chore] 코드 병합 및 최신화
  highpitch/App/AppDelegate.swift
  highpitch/App/HighPitchApp.swift
Labels: Chore

#100 [Fix] onboarding 수정
  highpitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  highpitch/Presentation/MainWindow/OnboardingView/OnboardingViewStore.swift
  highpitch/Presentation/Settings/SettingsView.swift
Labels: Fix

#101 [Fix] 실시간 STT 시간 한계 조정
  highpitch/Managers/ProjectManagers/ProjectManager.swift
  highpitch/Managers/SystemManagers/SystemManager.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
Labels: Fix
